### ISSUE TITLE
Zeyrek lemmatizes "içişleri" to "içmek"

### ISSUE THREAD

**Issue by abhi-kr-2100** [obulat/zeyrek#16]
I'm not Turkish, but as far as I know, this is incorrect. _İçmek_ means to drink whereas _İçişleri_ means interior; quite different words semantically.

**Comment by obulat** [comment]
Thank you for reporting, @abhi-kr-2100 ! You are right that these words don't have the same lemma. If I remember correctly, lemmatizer is very dumb, and it simply returns the first analysis result. This is not always the correct one, as in this case. Unfortunately, I don't have a clear idea on how to implement the selection of the best lemma from a list of options.
You can get all possible options if you use analyzer instead of lemmatizer.
